### ISSUE TITLE
Normal values for metrics

### ISSUE THREAD

**Issue by roryk** [ParkerLab/ataqv#13]
Hi everyone,

It's not mentioned in the documentation anywhere, do you have a suggestion for ranges of normal values of things like SMR, FLDD, TSS enrichment, peak duplicate ratio and what not look like?

**Comment by porchard** [comment]
Hi Rory,

You’re correct, we haven’t posted recommendations anywhere. We haven’t done that just because there are a variety of variables that are expected to influence the metrics, such as the quality of the reference genome, whether the sample was from a cell line or from a primary tissue, etc. As part of the ataqv manuscript we uniformly processed ATAC-seq data from 27 different publications (human + mouse), made ataqv HTML reports for all of them, and made those interactive reports available [here](https://theparkerlab.med.umich.edu/data/porchard/ataqv-public-survey/) so that people can have a look at them to get an idea of what the distributions of the various metrics look like in published datasets. I hope that will help users calibrate expectations. Also, there are a few figures in the manuscript (link [here](https://www.sciencedirect.com/science/article/pii/S240547122030079X)) that might be helpful:

1)	Fig 1D shows TSS enrichment and median fragment length for all 693 bulk ATAC-seq libraries processed in the manuscript. Median fragment length is not actually in the HTML report – it’s just meant to summarize the fragment length distribution in that figure, and it can be calculated from the JSON files if so desired. Perhaps I’ll see about adding it to the HTML report at some point as it’s a rather intuitive metric.
2)	Fig S3 shows TSS enrichment curves for all libraries in two publications.

For metrics relating to general mapping quality – percentage of read pairs properly mapped, percentage of reads unmapped, etc – it’s generally pretty clear when something is wrong. It’s good to check those just to make sure there wasn’t a mistake in mapping parameters or some kind of sample contamination. Besides sanity-checking the mapping statistics, when we QC bulk ATAC-seq data the metrics we tend to focus on are TSS enrichment, % mitochondrial, % duplicate, % of reads in peaks, % HQAA (that will also be affected by % mitochondrial and % duplicate, since mitochondrial reads and duplicate reads do not quality as high-quality autosomal). One needs to keep in mind that several metrics such as % duplicates and number of peaks (and therefore % of reads in peaks) may vary with technical parameters such as sequencing depth. If one is looking at a sizeable number of libraries, and one feels safe in assuming that most of them did not fail, then looking at the distributions of some of those key metrics and flagging the outliers is a good approach.

Just for reference, I’ll point out that ENCODE has their thresholds for human and mouse listed on their webpage [here](https://www.encodeproject.org/atac-seq/). Note that they give different thresholds for different reference genomes and for different TSS annotations, and those thresholds are quite variable across genomes/annotations. Also, ataqv calculates TSS enrichment in a different manner than ENCODE, so ataqv tends to report slightly lower TSS enrichment values than ENCODE – maybe one or two points lower based on my experience with some of the public data. 

I hope that's helpful.

**Comment by roryk** [comment]
Thanks so much! Sorry for not closing or responding. The paper was super helpful and looking through the reports to get a ballpark of what makes sense was really helpful.

**Comment by porchard** [comment]
Excellent! Glad it was helpful. I hope this issue will turn into a useful reference for others.
