### ISSUE TITLE
Should input alignment file be shifted to account for tn5 transposition?

### ISSUE THREAD

**Issue by owenwilkins** [ParkerLab/ataqv#31]
hello, thank you for this tool. I have a quick question that i was hoping someone could answer. while unlikely to make much of a difference, I was wondering if the input BAM should technically be shifted to account for the tn5 transposition?

**Comment by porchard** [comment]
Hi Owen,

We don't do any shifting prior to running ataqv. The exact Tn5 transposition location is only of interest in high-resolution analyses such as footprinting. Since ataqv is for general QC, there's no need to shift. Most of the metrics -- mapping rates, etc -- would show no change, and any changes that occur in other metrics will be insignificant.

**Comment by owenwilkins** [comment]
great, thats what I figured. thanks for the quick response.
