### ISSUE TITLE
html report error 

### ISSUE THREAD

**Issue by Mesi395** [ParkerLab/ataqv#34]
Hello, 
I ran the ataqv 1.3.1 on my 10X scATAC output file and got a sensible .json report, however, when I try to view it in the index.html form after running mkarv the webpage appears empty. 
Can you please advise what I should change to see the plots correctly?
Thank you

The lines I ran: 

#to get the .json file
ataqv --autosomal-reference-file /fast/AG_Junker/eratkai/data/ref_genomes/jmref/GRCz11/fasta/autosomal_ref_1.txt --peak-file /fast/AG_Junker/eratkai/data/ER_data/scA9_3dpiH/scA9_3dpiH/outs/filtered_peak_bc_matrix/peaks.bed --name H9_3 --metrics-file /fast/AG_Junker/eratkai/data/ER_data/scA9_3dpiH/scA9_objects/H9_ataqv/H9_3_metrics.json.gz --nucleus-barcode-tag /fast/AG_Junker/eratkai/data/ER_data/scA9_3dpiH/scA9_3dpiH/outs/filtered_peak_bc_matrix/barcodes.tsv dr11 /fast/AG_Junker/eratkai/data/ER_data/scA9_3dpiH/scA9_3dpiH/outs/possorted_bam.bam > /fast/AG_Junker/eratkai/data/ER_data/scA9_3dpiH/scA9_objects/H9_ataqv/H9_3.ataqv.out

#to get the index.html file
mkarv H9_3 /fast/AG_Junker/eratkai/data/ER_data/scA9_3dpiH/scA9_objects/H9_ataqv/H9_3_metrics.json.gz

**Comment by porchard** [comment]
Hi @Mesi395 -- are you removing the index.html file from it's location in the ataqv output directory (e.g., running ataqv on a server, and then downloading only the index.html file onto your local machine)? In order to view the ataqv html report, you need to download the entire ataqv output directory -- if you download the index.html file alone and open it in your browser, it'll be missing the data files it needs to read to generate the plots / tables.

Let me know if that is the issue?

**Comment by Mesi395** [comment]
ah yes, that makes a lot of sense, and it works. Thank you!

**Comment by porchard** [comment]
Great! Thanks for the follow-up
