### ISSUE TITLE
Minify the configuration.js

### ISSUE THREAD

**Issue by raivivek** [ParkerLab/ataqv#6]
The `configuration.js` generated by ataqv can be quite big (in my case it was about 15 MB). Guess could be minified to save time/bandwidth.

**Comment by umijh** [comment]
Thanks for the suggestion. The configuration.js is already effectively minified, as there's no white space or user-friendly formatting. The next step would be mangling the names, as with Google's Closure compiler, but the bulk of the file is usually numeric values. That leaves compression, which does significantly reduce the file size, but doesn't work for one of the two main usage scenarios for ataqv, loading a viewer from a local directory.

In the other expected scenario, hosting a viewer instance on a web server, the output is typically compressed on the fly by the web server. It's also usually possible to precompress the file and configure the web server to deliver it as-is, but the overhead of compression is not usually noticeable for low-volume resources like this. Either way, the download/response time should be minimized.

So, this is a long-winded way of saying wontfix, because the added complexity in ataqv wouldn't do as much for the user experience as simply hosting the viewer instance on a properly-configured web server.

**Comment by raivivek** [comment]
Thanks! This was informative.
