### ISSUE TITLE
Which BAM file to provide?

### ISSUE THREAD

**Issue by roryk** [ParkerLab/ataqv#8]
Hi everyone,

Thanks for making such a nice tool. When we run ATAQ-seq, we usually separate out the different nucleosome free, mononucleosome, dinucleosome and trinucleosome fractions, call peaks separately on each of the fractions, and focus on the nucleosome free peaks for the downstream analysis. Is `ataqv` expecting us to be passing on just the nucleosome-free regions? Or is the assumption we just called peaks on everything?

**Comment by porchard** [comment]
Glad you find it helpful! Our usual pre-ataqv workflow is: trim adapters, map, mark duplicates, filter to quality non-duplicate autosomal read pairs, and call peaks (on a single bam file containing all reads regardless of fragment length). We then pass that peak list and the bam file with duplicates marked (i.e., before filtering) to ataqv. This is probably what most users want, since people generally want to check the complete fragment length distribution, % mitochondrial contamination, % of reads in peaks, etc., and for general QC purposes those should be calculated using all fragments and before any filtering.

If in your downstream analysis you only use short reads and you therefore wish to gather statistics about that fraction only, you could run ataqv twice -- once using the full bam file (which would enable you to check the complete fragment length distribution, mitochondrial fraction, etc., and therefore ensure that the experiment wasn't a complete failure), and once using the bam file containing only the short reads. In that case you could pass both of the resulting JSON files to ataqv for simultaneous visualization in the HTML report.

**Comment by roryk** [comment]
Thank you for the clarification!
